### ISSUE TITLE
USER STORY: Copy bug tickets from sourceForge repo to here

### ISSUE THREAD

**Issue by joe-sonrichard** [CedarvilleCS/CedarLogic#27]
## Describe User Story
As has already been done with open feature tickets, all the open bug tickets need to be copied over to this repository. 

## Context
In order for all development to move here, we need to capture everything known about the product from sourceForge.

## Sub-Tasks
For every bug:
 - [x] Copy content into a bug report here and try to translate at least a little.
 - [x] Paste link to original bug report in new bug report
 - [x] Paste link to new bug report in original bug report.
