### ISSUE TITLE
dev-v2.4 - multiple changes for v2.4

### ISSUE THREAD

**Issue by JoeHCQ1** [CedarvilleCS/CedarLogic#46]
Objectives for v2.4:

v2.4 is primarily focused on the logic and the logic/gui interface, not the GUI.

- 95% unit test coverage over the logic
- Improved modularity (GUI should only interact with one Logic class)
- Improved CI/CD quality control
- Decreased LOC

Branch for epic: https://github.com/CedarvilleCS/CedarLogic/tree/dev-v2.4

Tickets in this epic:
- [ ] Add better documentation and comments for explanatory and user assistance.
- [ ] Auto-populate release artifacts for tags (CI/CD)
- [ ] Verify all unit tests pass in all PRs (CI/CD)
- [ ] Integrate logic changes with GUI (coding)
- [ ] Add Unit Testing (coding)
- [ ] #45 
- [x] #44 
- [ ] #43 
- [ ] #34 
- [ ] #10 
- [ ] #7 
- [ ] #6 
- [ ] #2
